### PR TITLE
Breaking change: Compatibility with jQuery 3

### PR DESCRIPTION
**Pull request by jaredbeck**
This PR is just to get the ball rolling. It'll still need documentation, etc.

### CODE REVIEW

**Comment by jaredbeck** [comment]
Fixes https://github.com/hazzik/livequery/issues/14

**Comment by jaredbeck** [comment]
> Plugins that need to use a selector string within their plugin can require it as a parameter of the method.
> https://api.jquery.com/selector/

**Comment by jaredbeck** [comment]
Four month ping, please review.

**Comment by hazzik** [comment]
Hi @jaredbeck. Thanks for the contribution. The tests are failing. I would expect to have 2 sets of tests: jquery <3 && jquery >=3.

**Comment by jaredbeck** [comment]
> The tests are failing. I would expect to have 2 sets of tests: jquery <3 && jquery >=3.

Thanks for reviewing. `test/lib/jquery.min.js` is currently `v2.0.3`. Should we start by renaming that file to something like `jquery-2.0.3.min.js` and adding another file for v3?

**Comment by ghost** [comment]
I used it with this and it didn't work:

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" language="javascript"></script>

**Comment by ghost** [comment]
And with this it works:
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js" language="javascript"></script>

**Comment by jaredbeck** [comment]
Closing due to inactivity.

**Pull request closed without merging**
